"""init

Revision ID: 27e80d420716
Revises: 
Create Date: 2026-01-26 15:51:39.695084

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '27e80d420716'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profiles',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('apple_user_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('sex', sa.Enum('MALE', 'FEMALE', name='sex'), nullable=True),
    sa.Column('birth_date', sa.DateTime(), nullable=True),
    sa.Column('height_cm', sa.Float(), nullable=True),
    sa.Column('current_weight_kg', sa.Float(), nullable=True),
    sa.Column('activity_level', sa.Enum('SEDENTARY', 'LIGHT', 'MODERATE', 'ACTIVE', 'VERY_ACTIVE', name='activitylevel'), nullable=False),
    sa.Column('goal_type', sa.Enum('CUT', 'MAINTAIN', 'BULK', name='goaltype'), nullable=False),
    sa.Column('goal_rate_kg_per_week', sa.Float(), nullable=False),
    sa.Column('target_weight_kg', sa.Float(), nullable=True),
    sa.Column('use_metric', sa.Boolean(), nullable=False),
    sa.Column('daily_water_goal_ml', sa.Integer(), nullable=False),
    sa.Column('protein_per_kg', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_profiles')),
    sa.UniqueConstraint('apple_user_id', name=op.f('uq_user_profiles_apple_user_id'))
    )
    op.create_index(op.f('ix_user_profiles_email'), 'user_profiles', ['email'], unique=True)
    op.create_table('body_weight_entries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('body_fat_percent', sa.Float(), nullable=True),
    sa.Column('muscle_mass_kg', sa.Float(), nullable=True),
    sa.Column('water_percent', sa.Float(), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=False),
    sa.Column('local_id', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_body_weight_entries_user_id_user_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_body_weight_entries'))
    )
    op.create_index(op.f('ix_body_weight_entries_timestamp'), 'body_weight_entries', ['timestamp'], unique=False)
    op.create_index(op.f('ix_body_weight_entries_user_id'), 'body_weight_entries', ['user_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', 'TOOL', name='messagerole'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_call_id', sa.String(length=100), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('conversation_id', sa.String(length=100), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=False),
    sa.Column('local_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_chat_messages_user_id_user_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chat_messages'))
    )
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_chat_messages_timestamp'), 'chat_messages', ['timestamp'], unique=False)
    op.create_index(op.f('ix_chat_messages_user_id'), 'chat_messages', ['user_id'], unique=False)
    op.create_table('macro_targets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.Column('bmr', sa.Integer(), nullable=True),
    sa.Column('tdee', sa.Integer(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_macro_targets_user_id_user_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_macro_targets')),
    sa.UniqueConstraint('user_id', name=op.f('uq_macro_targets_user_id'))
    )
    op.create_table('meals',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('meal_type', sa.Enum('BREAKFAST', 'LUNCH', 'DINNER', 'SNACK', 'OTHER', name='mealtype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_calories', sa.Integer(), nullable=False),
    sa.Column('total_protein_g', sa.Float(), nullable=False),
    sa.Column('total_carbs_g', sa.Float(), nullable=False),
    sa.Column('total_fat_g', sa.Float(), nullable=False),
    sa.Column('total_fiber_g', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=500), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=False),
    sa.Column('local_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_meals_user_id_user_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_meals'))
    )
    op.create_index(op.f('ix_meals_timestamp'), 'meals', ['timestamp'], unique=False)
    op.create_index(op.f('ix_meals_user_id'), 'meals', ['user_id'], unique=False)
    op.create_table('progress_snapshots',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('weight_7d_avg', sa.Float(), nullable=True),
    sa.Column('weight_change_7d', sa.Float(), nullable=True),
    sa.Column('avg_calories', sa.Integer(), nullable=True),
    sa.Column('avg_protein_g', sa.Float(), nullable=True),
    sa.Column('avg_carbs_g', sa.Float(), nullable=True),
    sa.Column('avg_fat_g', sa.Float(), nullable=True),
    sa.Column('calorie_adherence_percent', sa.Float(), nullable=True),
    sa.Column('protein_adherence_percent', sa.Float(), nullable=True),
    sa.Column('avg_steps', sa.Integer(), nullable=True),
    sa.Column('workouts_count', sa.Integer(), nullable=True),
    sa.Column('total_workout_min', sa.Integer(), nullable=True),
    sa.Column('avg_water_ml', sa.Integer(), nullable=True),
    sa.Column('water_goal_hit_days', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_progress_snapshots_user_id_user_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_progress_snapshots'))
    )
    op.create_index(op.f('ix_progress_snapshots_date'), 'progress_snapshots', ['date'], unique=False)
    op.create_index(op.f('ix_progress_snapshots_user_id'), 'progress_snapshots', ['user_id'], unique=False)
    op.create_table('saved_foods',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('brand', sa.String(length=200), nullable=True),
    sa.Column('source', sa.Enum('MANUAL', 'OPEN_FOOD_FACTS', 'BARCODE', 'VISION', 'CHAT', name='foodsource'), nullable=False),
    sa.Column('calories_per_100g', sa.Integer(), nullable=False),
    sa.Column('protein_per_100g', sa.Float(), nullable=False),
    sa.Column('carbs_per_100g', sa.Float(), nullable=False),
    sa.Column('fat_per_100g', sa.Float(), nullable=False),
    sa.Column('fiber_per_100g', sa.Float(), nullable=True),
    sa.Column('default_serving_g', sa.Float(), nullable=False),
    sa.Column('serving_unit', sa.String(length=50), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('times_used', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('off_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_saved_foods_user_id_user_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_foods'))
    )
    op.create_index(op.f('ix_saved_foods_barcode'), 'saved_foods', ['barcode'], unique=False)
    op.create_index(op.f('ix_saved_foods_user_id'), 'saved_foods', ['user_id'], unique=False)
    op.create_table('steps_daily',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('steps', sa.Integer(), nullable=False),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('flights_climbed', sa.Integer(), nullable=True),
    sa.Column('active_energy_kcal', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_steps_daily_user_id_user_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_steps_daily'))
    )
    op.create_index(op.f('ix_steps_daily_date'), 'steps_daily', ['date'], unique=False)
    op.create_index(op.f('ix_steps_daily_user_id'), 'steps_daily', ['user_id'], unique=False)
    op.create_table('water_entries',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('amount_ml', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_synced', sa.Boolean(), nullable=False),
    sa.Column('local_id', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_water_entries_user_id_user_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_water_entries'))
    )
    op.create_index(op.f('ix_water_entries_timestamp'), 'water_entries', ['timestamp'], unique=False)
    op.create_index(op.f('ix_water_entries_user_id'), 'water_entries', ['user_id'], unique=False)
    op.create_table('workout_plans',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('workout_type', sa.Enum('STRENGTH', 'CARDIO', 'HIIT', 'FLEXIBILITY', 'SPORTS', 'WALKING', 'RUNNING', 'CYCLING', 'SWIMMING', 'OTHER', name='workouttype'), nullable=False),
    sa.Column('scheduled_days', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('estimated_duration_min', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_workout_plans_user_id_user_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_plans'))
    )
    op.create_index(op.f('ix_workout_plans_user_id'), 'workout_plans', ['user_id'], unique=False)
    op.create_table('food_items',
    sa.Column('meal_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'OPEN_FOOD_FACTS', 'BARCODE', 'VISION', 'CHAT', name='foodsource'), nullable=False),
    sa.Column('grams', sa.Float(), nullable=False),
    sa.Column('serving_size', sa.Float(), nullable=True),
    sa.Column('serving_unit', sa.String(length=50), nullable=True),
    sa.Column('servings', sa.Float(), nullable=False),
    sa.Column('calories', sa.Integer(), nullable=False),
    sa.Column('protein_g', sa.Float(), nullable=False),
    sa.Column('carbs_g', sa.Float(), nullable=False),
    sa.Column('fat_g', sa.Float(), nullable=False),
    sa.Column('fiber_g', sa.Float(), nullable=True),
    sa.Column('sodium_mg', sa.Float(), nullable=True),
    sa.Column('sugar_g', sa.Float(), nullable=True),
    sa.Column('saturated_fat_g', sa.Float(), nullable=True),
    sa.Column('barcode', sa.String(length=50), nullable=True),
    sa.Column('off_product_id', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('portion_description', sa.String(length=200), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meal_id'], ['meals.id'], name=op.f('fk_food_items_meal_id_meals'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_food_items'))
    )
    op.create_index(op.f('ix_food_items_meal_id'), 'food_items', ['meal_id'], unique=False)
    op.create_table('vision_analyses',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('image_hash', sa.String(length=64), nullable=True),
    sa.Column('raw_response', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parsed_items', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('totals', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('was_accepted', sa.Boolean(), nullable=False),
    sa.Column('was_edited', sa.Boolean(), nullable=False),
    sa.Column('linked_meal_id', sa.UUID(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=False),
    sa.Column('analysis_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['linked_meal_id'], ['meals.id'], name=op.f('fk_vision_analyses_linked_meal_id_meals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_vision_analyses_user_id_user_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_vision_analyses'))
    )
    op.create_index(op.f('ix_vision_analyses_user_id'), 'vision_analyses', ['user_id'], unique=False)
    op.create_table('workout_exercises',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('muscle_group', sa.Enum('CHEST', 'BACK', 'SHOULDERS', 'BICEPS', 'TRICEPS', 'FOREARMS', 'CORE', 'QUADS', 'HAMSTRINGS', 'GLUTES', 'CALVES', 'FULL_BODY', 'CARDIO', name='musclegroup'), nullable=True),
    sa.Column('equipment', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('reps_min', sa.Integer(), nullable=True),
    sa.Column('reps_max', sa.Integer(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('rest_sec', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('superset_group', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['workout_plans.id'], name=op.f('fk_workout_exercises_plan_id_workout_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_exercises'))
    )
    op.create_index(op.f('ix_workout_exercises_plan_id'), 'workout_exercises', ['plan_id'], unique=False)
    op.create_table('workout_logs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('workout_type', sa.Enum('STRENGTH', 'CARDIO', 'HIIT', 'FLEXIBILITY', 'SPORTS', 'WALKING', 'RUNNING', 'CYCLING', 'SWIMMING', 'OTHER', name='workouttype'), nullable=False),
    sa.Column('source', sa.Enum('MANUAL', 'HEALTH_KIT', 'CHAT', name='logsource'), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('calories_burned', sa.Integer(), nullable=True),
    sa.Column('avg_heart_rate', sa.Integer(), nullable=True),
    sa.Column('max_heart_rate', sa.Integer(), nullable=True),
    sa.Column('distance_km', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('health_kit_id', sa.String(length=100), nullable=True),
    sa.Column('is_synced', sa.Boolean(), nullable=False),
    sa.Column('local_id', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['workout_plans.id'], name=op.f('fk_workout_logs_plan_id_workout_plans'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['user_profiles.id'], name=op.f('fk_workout_logs_user_id_user_profiles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_logs')),
    sa.UniqueConstraint('health_kit_id', name=op.f('uq_workout_logs_health_kit_id'))
    )
    op.create_index(op.f('ix_workout_logs_start_time'), 'workout_logs', ['start_time'], unique=False)
    op.create_index(op.f('ix_workout_logs_user_id'), 'workout_logs', ['user_id'], unique=False)
    op.create_table('workout_set_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('exercise_name', sa.String(length=200), nullable=False),
    sa.Column('set_number', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('duration_sec', sa.Integer(), nullable=True),
    sa.Column('distance_m', sa.Float(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('is_warmup', sa.Boolean(), nullable=False),
    sa.Column('is_dropset', sa.Boolean(), nullable=False),
    sa.Column('rpe', sa.Integer(), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['log_id'], ['workout_logs.id'], name=op.f('fk_workout_set_logs_log_id_workout_logs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_set_logs'))
    )
    op.create_index(op.f('ix_workout_set_logs_log_id'), 'workout_set_logs', ['log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workout_set_logs_log_id'), table_name='workout_set_logs')
    op.drop_table('workout_set_logs')
    op.drop_index(op.f('ix_workout_logs_user_id'), table_name='workout_logs')
    op.drop_index(op.f('ix_workout_logs_start_time'), table_name='workout_logs')
    op.drop_table('workout_logs')
    op.drop_index(op.f('ix_workout_exercises_plan_id'), table_name='workout_exercises')
    op.drop_table('workout_exercises')
    op.drop_index(op.f('ix_vision_analyses_user_id'), table_name='vision_analyses')
    op.drop_table('vision_analyses')
    op.drop_index(op.f('ix_food_items_meal_id'), table_name='food_items')
    op.drop_table('food_items')
    op.drop_index(op.f('ix_workout_plans_user_id'), table_name='workout_plans')
    op.drop_table('workout_plans')
    op.drop_index(op.f('ix_water_entries_user_id'), table_name='water_entries')
    op.drop_index(op.f('ix_water_entries_timestamp'), table_name='water_entries')
    op.drop_table('water_entries')
    op.drop_index(op.f('ix_steps_daily_user_id'), table_name='steps_daily')
    op.drop_index(op.f('ix_steps_daily_date'), table_name='steps_daily')
    op.drop_table('steps_daily')
    op.drop_index(op.f('ix_saved_foods_user_id'), table_name='saved_foods')
    op.drop_index(op.f('ix_saved_foods_barcode'), table_name='saved_foods')
    op.drop_table('saved_foods')
    op.drop_index(op.f('ix_progress_snapshots_user_id'), table_name='progress_snapshots')
    op.drop_index(op.f('ix_progress_snapshots_date'), table_name='progress_snapshots')
    op.drop_table('progress_snapshots')
    op.drop_index(op.f('ix_meals_user_id'), table_name='meals')
    op.drop_index(op.f('ix_meals_timestamp'), table_name='meals')
    op.drop_table('meals')
    op.drop_table('macro_targets')
    op.drop_index(op.f('ix_chat_messages_user_id'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_timestamp'), table_name='chat_messages')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_body_weight_entries_user_id'), table_name='body_weight_entries')
    op.drop_index(op.f('ix_body_weight_entries_timestamp'), table_name='body_weight_entries')
    op.drop_table('body_weight_entries')
    op.drop_index(op.f('ix_user_profiles_email'), table_name='user_profiles')
    op.drop_table('user_profiles')
    # ### end Alembic commands ###
